package dev.flixw.metrics;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;

/** Creates an explicit starter policy and a native report baseline without overwriting either. */
final class Initializer {
    static final String BASELINE_FILE = "metrics-baseline.json";

    private static final String POLICY = """
        # flixw metrics project policy
        #
        # Defaults are active while these examples remain commented. Uncomment only decisions
        # your project has reviewed; unknown or incomplete settings fail instead of being ignored.

        # Override a numeric threshold or disable a rule:
        # rules.definition-too-long.limit=80
        # rules.dense.enabled=false

        # Keep generated sources available to the compiler but out of located quality signals:
        # exclusions.generated.file=src/generated/**
        # exclusions.generated.reason=generated by the schema compiler

        # Suppress established debt narrowly and with an optional review date:
        # suppressions.legacy.rule=too-many-parameters
        # suppressions.legacy.subject=Legacy.*
        # suppressions.legacy.reason=replace after the protocol migration
        # suppressions.legacy.until=2027-01-31
        """;

    private Initializer() { }

    static void preflight(Path root) {
        Path policy = root.resolve(MetricsConfig.FILE);
        Path baseline = root.resolve(BASELINE_FILE);
        if (Files.exists(policy)) throw exists(policy);
        if (Files.exists(baseline)) throw exists(baseline);
    }

    static String write(Path root, String baselineJson) throws IOException {
        preflight(root);
        Path policy = root.resolve(MetricsConfig.FILE);
        Path baseline = root.resolve(BASELINE_FILE);
        boolean policyCreated = false;
        boolean baselineCreated = false;
        try {
            Files.writeString(policy, POLICY, StandardOpenOption.CREATE_NEW);
            policyCreated = true;
            Files.writeString(baseline, baselineJson, StandardOpenOption.CREATE_NEW);
            baselineCreated = true;
        } catch (IOException e) {
            if (baselineCreated) cleanup(baseline, e);
            if (policyCreated) cleanup(policy, e);
            throw e;
        }
        return "created " + MetricsConfig.FILE + "\n"
            + "created " + BASELINE_FILE + "\n"
            + "CI: ./flixw metrics report --baseline " + BASELINE_FILE
            + " --fail-on-new warning\n";
    }

    /** Best-effort rollback that preserves the exception which made rollback necessary. */
    static void cleanup(Path path, IOException original) {
        try {
            Files.deleteIfExists(path);
        } catch (IOException cleanupFailure) {
            original.addSuppressed(cleanupFailure);
        }
    }

    private static Main.Usage exists(Path path) {
        return new Main.Usage("refusing to overwrite " + path
            + "; move or remove it before running init");
    }
}
